name: time-series-labs
channels:
  - pytorch
  - saravji
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - "cudatoolkit<=10.2"
  - pytorch=1.8.1
  - ipykernel=5.5.3
  - scikit-learn=0.24.1
  - matplotlib=3.4.1
  - libarchive=3.5.1
  - pandas=1.2.4
  - notebook=6.3.0
  - pmdarima=1.2.0
  - pandas-datareader=0.9.0
  - seaborn=0.11.1
  - sktime=0.5.3

