name: Test Jupyter Notebook 
on:
  push:
    branches:
      - main

  pull_request:
    types: [synchronize, review_requested]

jobs:
  build:
    name: Test solution folder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: time-series-labs

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pip
          pip install flake8_nb
          
      - name: Execute Flake8 to test
        shell: bash -l {0}
        run: |
          for i in **/Solution/**; do 
            flake8_nb --select=E9,F63,F7 --notebook-cell-format '{nb_path}:code_cell#{code_cell_count}' "$i"
          done